#!/bin/sh
# File generated by ocamlbuild

cd /Users/apple/git/w4115PLT

rm -f src/project/ast.cmi
rm -f src/project/ast.cmo
rm -f src/project/calc.cmi
rm -f src/project/calc.cmo
rm -f src/project/parser.cmi
rm -f src/project/parser.cmo
rm -f src/project/parser.ml
rm -f src/project/parser.mli
rm -f src/project/scanner.cmi
rm -f src/project/scanner.cmo
rm -f src/project/scanner.ml
# Also clean the script itself
rm -f /Users/apple/git/w4115PLT/_build/sanitize.sh
